onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider TB_TOP_LEVEL
add wave -noupdate /tb_avm_instruction_gen_v04_public/stream01
add wave -noupdate -height 29 /tb_avm_instruction_gen_v04_public/stream02
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/clk_gen_o
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/rst_proc_o
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/rst_run_proc_o
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_adri_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_adro_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_dout_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_stb_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_cyc_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_we_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_ack_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_din_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_clear_epoch_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/tb_wb_thres_oi
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/done
add wave -noupdate -group TB_TOP_LEVEL -height 29 /tb_avm_instruction_gen_v04_public/stream02
add wave -noupdate -group TB_TOP_LEVEL /tb_avm_instruction_gen_v04_public/stream01
add wave -noupdate -divider TOP_LEVEL
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_adr_i
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_clk_i
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_cyc_i
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_dat_i
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_rst_i
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_stb_i
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_we_i
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/ctrl_int_o
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_ack_o
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/wb_dat_o
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/addr_i_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/addr_j_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dbias_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dout1_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dout2_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dout3_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dout4_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dout5_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dout7_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/ds_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dt_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dw_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/dy_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_bias2_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_bias3_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_bias5_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_s3_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_s4_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_s5_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_t3_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_t4_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_t5_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_w2_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_w3_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_w4_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_w5_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_w7_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_y1_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_y3_oi
add wave -noupdate -group TOP_LEVEL /tb_avm_instruction_gen_v04_public/U_0/we_y5_oi
add wave -noupdate -divider PERCEPTRON
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/clk_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dbias_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ds_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dt_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dw_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dy_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/rst_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/wb_adr_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/wb_cyc_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/wb_dat_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/wb_stb_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/wb_we_i
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/addr_i_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/addr_j_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_int_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dout1_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dout2_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dout3_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dout4_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dout5_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/dout7_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/wb_ack_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/wb_dat_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_bias2_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_bias3_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_bias5_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_s3_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_s4_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_s5_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_t3_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_t4_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_t5_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_w2_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_w3_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_w4_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_w5_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_w7_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_y1_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_y3_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/we_y5_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnt_alllat_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnteni1_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnteni2_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnteni3_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnteni4_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnteni5_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnteni7_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cntenj1_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cntenj2_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cntenj3_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cntenj4_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cntenj5_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cntenj7_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnti_end_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cnti_rdy_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cntj_end_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/cntj_rdy_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_bias_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_clear_epoch_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_complete_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_din_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_dout_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_dout_valid_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_epoch_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_int4_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_int6_o
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_maxepoch_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_memerr_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_not_rdy6_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_offset_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rd_vec_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rdlat_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rdy1_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rdy2_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rdy3_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rdy4_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rdy5_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rdy6_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_rdy7_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_run7_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_start1_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_start2_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_start3_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_start4_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_start5_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_start6_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_thres_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_wchgd_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_wr_vec_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/ctrl_wrlat_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/rst_n_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/set_initi_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/set_initj_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/starti_val_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/startj_val_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/stopi_val_oi
add wave -noupdate -group PERCEPTRON /tb_avm_instruction_gen_v04_public/U_0/U_0/stopj_val_oi
add wave -noupdate -divider WISHBONE
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/clk_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_alllat_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_complete_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_dout_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_dout_valid_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_epoch_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_int_test_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_int_train_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_memerr_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_not_rdy6_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rdlat_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rdy1_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rdy2_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rdy3_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rdy4_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rdy5_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rdy6_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_run7_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_wrlat_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/rst_n_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_adr_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_cyc_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_dat_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_stb_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_we_i
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_bias_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_clear_epoch_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_din_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_int_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_maxepoch_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_offset_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rd_vec_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_set_starti_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_set_startj_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_start3_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_start4_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_start5_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_start6_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_starti_val_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_startj_val_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_stopi_val_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_stopj_val_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_thres_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_wr_vec_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_ack_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_dat_o
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_bias_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_complete_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_din_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_int_en_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_int_test_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_int_train_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_maxepoch_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_offset_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rd_vec_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_rdy_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_starti_val_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_startj_val_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_stat_a_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_stopi_val_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_stopj_val_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_thres_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/ctrl_wr_vec_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_adr_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_cyc_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_dat_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_stb_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/wb_we_reg
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/zero_net_addrs
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/zero_net_addrt
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/current_state
add wave -noupdate -group WISHBONE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_14/next_state
add wave -noupdate -divider FOR_LOOP_I
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/clk_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnten1_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnten2_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnten3_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnten4_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnten5_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnten7_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/rst_n_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/set_init_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/start_vali_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/stop_vali_i
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnt_end_o
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnt_rdy_o
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnt_val_o
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnt_end_reg
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnt_reg
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/cnten_reg
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/set_init_reg
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/current_state
add wave -noupdate -group FOR_LOOP_I /tb_avm_instruction_gen_v04_public/U_0/U_0/U_2/next_state
add wave -noupdate -divider FOR_LOOP_J
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/clk_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnten1_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnten2_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnten3_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnten4_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnten5_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnten7_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/rst_n_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/set_init_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/start_valj_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/stop_valj_i
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnt_end_o
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnt_rdy_o
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnt_val_o
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnt_end_reg
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnt_reg
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/cnten_reg
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/set_init_reg
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/current_state
add wave -noupdate -group FOR_LOOP_J /tb_avm_instruction_gen_v04_public/U_0/U_0/U_1/next_state
add wave -noupdate -divider CAL_Y
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/clk_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/cnti_end_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/cntj_end_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_rdlat_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_rdy7_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_start_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_thres_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_wrlat_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/dbias_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ds_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/dw_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/rst_n_i
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/cnteni_o
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/cntenj_o
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_rdy_o
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/dout_o
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/we_y_o
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_rdlat_reg
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_start_reg
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/ctrl_wrlat_reg
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/dbias_reg
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/dw_reg
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/y_inj_reg
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/current_state
add wave -noupdate -group CAL_Y /tb_avm_instruction_gen_v04_public/U_0/U_0/U_0/next_state
add wave -noupdate -divider CAL_W
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/clk_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/cnti_end_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/cntj_end_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_rdlat_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_rdy7_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_start_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_wrlat_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/dbias_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ds_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/dt_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/dw_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/dy_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/rst_n_i
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/cnteni_o
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/cntenj_o
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_rdy_o
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_wchgd_o
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/dout_o
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/we_bias_o
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/we_w_o
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_rdlat_reg
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_start_reg
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_wchgd_reg
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/ctrl_wrlat_reg
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/dbias_reg
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/dt_reg
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/dw_reg
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/current_state
add wave -noupdate -group CAL_W /tb_avm_instruction_gen_v04_public/U_0/U_0/U_8/next_state
add wave -noupdate -divider INIT
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/clk_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/cnti_end_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/cntj_end_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_bias_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_rdlat_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_rdy7_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_start_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_wrlat_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/rst_n_i
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/cnteni_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/cntenj_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_rdy_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/dout_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/we_bias_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/we_s_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/we_t_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/we_w_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/we_y_o
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_rdlat_reg
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_start_reg
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/ctrl_wrlat_reg
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/current_state
add wave -noupdate -group INIT /tb_avm_instruction_gen_v04_public/U_0/U_0/U_9/next_state
add wave -noupdate -divider TEST
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/clk_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/cnti_end_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/cntj_end_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_rdlat_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_rdy7_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_start_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_wrlat_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ds_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/dt_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/dw_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/offset_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/rst_n_i
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/cnteni_o
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/cntenj_o
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_int_o
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_rdy_o
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/dout_o
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/we_s_o
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/we_t_o
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/we_w_o
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_int_reg
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_rdlat_reg
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_start_reg
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/ctrl_wrlat_reg
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/dt_reg
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/dw_reg
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/current_state
add wave -noupdate -group TEST /tb_avm_instruction_gen_v04_public/U_0/U_0/U_10/next_state
add wave -noupdate -divider READ_WRITE
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/clk_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/cnti_end_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/cntj_end_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_din_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_rd_vec_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_rdlat_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_rdy7_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_start_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_wr_vec_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_wrlat_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/dbias_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ds_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/dt_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/dw_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/dy_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/rst_n_i
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/cnteni_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/cntenj_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_complete_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_dout_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_dout_valid_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_rdy_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/dout_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/we_bias_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/we_s_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/we_t_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/we_w_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/we_y_o
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_complete_reg
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_dout_reg
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_dout_valid_reg
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_rdlat_reg
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_start_reg
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/ctrl_wrlat_reg
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/current_state
add wave -noupdate -group READ_WRITE /tb_avm_instruction_gen_v04_public/U_0/U_0/U_11/next_state
add wave -noupdate -divider TRAINING
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/clk_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/cnti_rdy_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/cntj_rdy_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_clear_epoch_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_maxepoch_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_rdy1_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_rdy2_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_rdy7_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_start_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_wchgd_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/rst_n_i
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_epoch_o
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_int_o
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_not_rdy_o
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_rdy_o
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_start1_o
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_start2_o
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/cnti_rdy_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/cntj_rdy_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_clear_epoch_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_epoch_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_int_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_not_rdy_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_rdy1_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_rdy2_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/ctrl_start_reg
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/current_state
add wave -noupdate -group TRAINING /tb_avm_instruction_gen_v04_public/U_0/U_0/U_12/next_state
add wave -noupdate -divider LATENCY
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/clk_i
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/dw_i
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/rst_n_i
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/cnt_alllat_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/cnteni_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/cntenj_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_memerr_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_rdlat_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_rdy_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_run_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_wrlat_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/dout_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/we_w_o
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/cnt_alllat_reg
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_memerr_reg
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_rdlat_reg
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_rdy_reg
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_run_reg
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/ctrl_wrlat_reg
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/dw_reg
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/current_state
add wave -noupdate -group LATENCY /tb_avm_instruction_gen_v04_public/U_0/U_0/U_13/next_state
add wave -noupdate -divider S-MEMORY
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/clk_i
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/we_i
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/d_i
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/addr_i
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/d_o
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/addr_reg
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/din_reg
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/we_reg
add wave -noupdate -group S-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_0/s_ram
add wave -noupdate -divider T-MEMORY
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/clk_i
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/we_i
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/d_i
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/addr_i
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/d_o
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/addr_reg
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/din_reg
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/we_reg
add wave -noupdate -group T-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_1/t_ram
add wave -noupdate -divider Y-MEMORY
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/clk_i
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/we_i
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/d_i
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/addr_i
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/d_o
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/addr_reg
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/din_reg
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/we_reg
add wave -noupdate -group Y-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_2/t_ram
add wave -noupdate -divider BIAS-MEMORY
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/clk_i
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/we_i
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/d_i
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/addr_i
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/d_o
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/addr_reg
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/din_reg
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/we_reg
add wave -noupdate -group BIAS-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_3/t_ram
add wave -noupdate -divider W-MEMORY
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/clk_i
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/we_i
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/d_i
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/addr_i
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/d_o
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/addr_reg
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/din_reg
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/we_reg
add wave -noupdate -group W-MEMORY /tb_avm_instruction_gen_v04_public/U_0/U_1/U_4/w_ram
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 450
configure wave -valuecolwidth 120
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ns} {753333 ns}
